
import { Geist, Geist_Mono } from "next/font/google";
import SessionWrapper from "./components/SessionWrapper";
import { AuthProvider } from "./userInfoContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Linterest",
  description: "Generated by create next app",
  icons: {
    icon: "https://plus.unsplash.com/premium_photo-1668902221232-5908bec128f9?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
}; 

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionWrapper>
          <AuthProvider>{children}</AuthProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
